[("python-tutorial", "."),
 ("sourcecodegen/src/sourcecodegen", "sourcecodegen"),
 ("codemirror", "static/codemirror"),
 ("cappython", "cappython"),
 ("simplejson/simplejson", "simplejson"),
 ("data/__init__.py", "pypybits/__init__.py"),
 ("data/__init__.py", "cappython/__init__.py"),
 ("pypy/pypy/interpreter/pyparser/automata.py", "pypybits/automata.py"),
 ("pypy/pypy/interpreter/pyparser/grammar.py", "pypybits/grammar.py"),
 ("pypy/pypy/interpreter/pyparser/pythonparse.py", "pypybits/pythonparse.py"),
 ("pypy/pypy/interpreter/pyparser/pythonutil.py", "pypybits/pythonutil.py"),
 ("pypy/pypy/interpreter/pyparser/data/Grammar2.5", "pypybits/Grammar2.5"),
 ]
