[
    ("python-tutorial", "."),
    ("sourcecodegen/src/sourcecodegen", "sourcecodegen"),
    ("codemirror", "static/codemirror"),
    ("cappython", "cappython"),
    ("simplejson/simplejson", "simplejson"),
    ("data/__init__.py", "pypybits/__init__.py"),
    ("data/__init__.py", "cappython/__init__.py"),
    ("pypy/pypy/interpreter/pyparser/automata.py", "pypybits/automata.py"),
    ("pypy/pypy/interpreter/pyparser/grammar.py", "pypybits/grammar.py"),
    ("pypy/pypy/interpreter/pyparser/pythonparse.py", 
     "pypybits/pythonparse.py"),
    ("pypy/pypy/interpreter/pyparser/pythonutil.py", "pypybits/pythonutil.py"),
    ("pypy/pypy/interpreter/pyparser/data/Grammar2.5", "pypybits/Grammar2.5"),
    ("pypy/pypy/tool/uid.py", "pypybits/uid.py"),
    ("pypy/pypy/interpreter/stablecompiler/visitor.py", "pypybits/visitor.py"),
    ("pypy/lib-python/2.5.2/compiler/ast.py", "pypybits/ast.py"),
    ("pypy/pypy/interpreter/pyparser/tuplebuilder.py", 
     "pypybits/tuplebuilder.py"),
    ("pypy/lib-python/2.5.2/compiler/transformer.py",
     "pypybits/transformer.py"),
    ("pypy/lib-python/2.5.2/compiler/__init__.py", "pypybits/compiler.py"),
    ("pypy/lib-python/2.5.2/compiler/consts.py", "pypybits/compilerconsts.py"),
    ("pypy/pypy/interpreter/astcompiler/consts.py", "pypybits/astconsts.py"),
    ("pypy/pypy/interpreter/pyparser/ebnfgrammar.py",
     "pypybits/ebnfgrammar.py"),
    ("pypy/pypy/interpreter/pyparser/ebnflexer.py", "pypybits/ebnflexer.py"),
    ("pypy/pypy/interpreter/pyparser/ebnfparse.py", "pypybits/ebnfparse.py"),
    ("pypy/pypy/interpreter/pyparser/error.py", "pypybits/error.py"),
    ("pypy/lib-python/2.5.2/compiler/misc.py", "pypybits/misc.py"),
    ("pypy/pypy/interpreter/pyparser/pythonlexer.py", 
     "pypybits/pythonlexer.py"),
 ]
