application: jython-tutorial
version: 7
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /.*
  script: main.py

